Feature/#768 increase okewo integration to sb3
it-at-m/digiwf-core pull request #1062
Opened 2023-11-29 16:08 UTC by StephanStrehlerCGI

### Description

Short description or comments

### Reference

Issues: closes #768

### Check-List

- [x] All Acceptance criteria of user story are met
- [ ] JUnit tests are written (60% CodeCov)
- [ ] [Internal Review]([https://github.com/it-at-m/digiwf-core/blob/dev/CHANGELOG.md](https://confluence.muenchen.de/display/MPdZ/Review+-+DigiWF)) is maintained
- [ ] Documentations [external](https://github.com/it-at-m/digiwf-core/tree/dev/docs) and [internal](https://wiki.muenchen.de/betriebshandbuch/index.php?title=DigiWF&sfr=betriebshandbuch) are completed
- [x] Smoketest successful (Manual E2E-Test depending on Change) 
- [x] No Branch waste left
- [ ] [Board](https://app.zenhub.com/workspaces/digiwf-621f70bf50ea1100120b7e93/board) is up-to-date
- [ ] Openshift environments are prepared (Secrets, etc.) and release-issue is maintained

2023-11-30 09:04 UTC, zambrovski requested changes
Please review the requested changes.

2023-11-30 09:04 UTC, zambrovski commented on digiwf-integrations/digiwf-okewo-integration/digiwf-okewo-integration-client/pom.xml
> +        <swagger.codegen.version>3.0.33</swagger.codegen.version>
why is it needed?

2023-11-30 09:04 UTC, zambrovski commented on digiwf-integrations/digiwf-okewo-integration/digiwf-okewo-integration-client/pom.xml
> +        <!-- Spring -->
drop it

2023-11-30 09:04 UTC, zambrovski commented on digiwf-integrations/digiwf-okewo-integration/digiwf-okewo-integration-client/pom.xml
> +            <plugin>
can be removed (is a part of default Maven plugin included into build)

2023-11-30 09:04 UTC, zambrovski commented on digiwf-integrations/digiwf-okewo-integration/digiwf-okewo-integration-client/pom.xml
> +                <version>7.0.1</version>
the version is managed, should not be here.

2023-11-30 09:04 UTC, zambrovski commented on digiwf-integrations/digiwf-okewo-integration/digiwf-okewo-integration-client/pom.xml
> +                        <id>generate-server-stubs</id>
the execution is probably called badly, we are generating client code here

2023-11-30 09:04 UTC, zambrovski commented on digiwf-integrations/digiwf-okewo-integration/digiwf-okewo-integration-client/pom.xml
> +                            <generateSupportingFiles>false</generateSupportingFiles>
if generate supporting files is set to false, why do we need to specify supporting files below? usually we use a .openapi-generator-ignore to exclude stuff.

2023-11-30 09:04 UTC, zambrovski commented on digiwf-integrations/digiwf-okewo-integration/digiwf-okewo-integration-client/pom.xml
> +            <plugin>
default plugin same as surefire, no need to list it

2023-11-30 09:04 UTC, zambrovski commented on digiwf-integrations/digiwf-okewo-integration/digiwf-okewo-integration-core/pom.xml
>              <groupId>org.springdoc</groupId>
this dependency is called differently in SPB3

2023-11-30 09:04 UTC, zambrovski commented on digiwf-integrations/digiwf-okewo-integration/digiwf-okewo-integration-core/src/main/resources/application.yml
> +      definition: functionRouter;sendMessage;
routing-expression: "headers['type']" missing?

2023-11-30 09:04 UTC, zambrovski commented on digiwf-integrations/digiwf-okewo-integration/digiwf-okewo-integration-service/pom.xml
> +            <version>3.3.1</version>
is managed, remove the version

2023-11-30 09:04 UTC, zambrovski commented on digiwf-integrations/digiwf-okewo-integration/digiwf-okewo-integration-core/src/main/resources/application.yml
> +management:
why this file is present in the core? it is slightly confusing... I believe it should be in service only. If you need it for the itest setup, please merge it with the application-itest.yaml

2023-11-30 09:04 UTC, zambrovski commented on digiwf-integrations/digiwf-okewo-integration/digiwf-okewo-integration-service/src/main/resources/application.yml
>      location: banner.txt
default

2023-11-30 09:04 UTC, zambrovski commented on digiwf-integrations/digiwf-okewo-integration/digiwf-okewo-integration-service/src/main/resources/application.yml
> +# FIXME: move to io.muenchendigital
why not doing it right now?

2023-11-30 09:04 UTC, zambrovski commented on digiwf-integrations/digiwf-okewo-integration/digiwf-okewo-integration-service/src/test/resources/application-itest.yml
> +management:
application-itest should only overwrite relevant properties. no reason to duplicate the entire file

2023-11-30 09:04 UTC, zambrovski commented on digiwf-integrations/digiwf-okewo-integration/digiwf-okewo-integration-starter/src/main/java/de/muenchen/oss/digiwf/okewo/integration/configuration/OkEwoIntegrationAutoConfiguration.java
> +                ApiClient.class,
this is strange and should not be needed. you may component scan the same component multiple time. why is this needed?

2023-11-30 09:04 UTC, zambrovski commented on digiwf-integrations/digiwf-okewo-integration/pom.xml
>          <maven.surefire.plugin.version>3.2.2</maven.surefire.plugin.version>
remove the version

2023-11-30 09:04 UTC, zambrovski commented on digiwf-integrations/digiwf-okewo-integration/pom.xml
> +        <dependency>
renamed - it is now called `digiwf-spring-logging-and-tracing`

2023-11-30 20:04 UTC, StephanStrehlerCGI commented on digiwf-integrations/digiwf-okewo-integration/digiwf-okewo-integration-client/pom.xml
> +            <plugin>
I don't know exactly what you mean. For it looks exacly like the other configurations in task-service or other integrations.

2023-11-30 20:04 UTC, StephanStrehlerCGI commented on digiwf-integrations/digiwf-okewo-integration/digiwf-okewo-integration-service/pom.xml
> +            <version>3.3.1</version>
For that we have to merge your draft branch first

2023-12-11 11:14 UTC, zambrovski approved these changes

2023-12-11 11:19 UTC, merged