Feature/#884 set formfields over query parameter
it-at-m/digiwf-core pull request #1083
Opened 2023-12-06 17:39 UTC by StephanStrehlerCGI

### Description

Short description or comments

### Reference

Issues: closes #884 

### Check-List

- [ ] All Acceptance criteria of user story are met
- [ ] JUnit tests are written (60% CodeCov)
- [ ] [Internal Review]([https://github.com/it-at-m/digiwf-core/blob/dev/CHANGELOG.md](https://confluence.muenchen.de/display/MPdZ/Review+-+DigiWF)) is maintained
- [ ] Documentations [external](https://github.com/it-at-m/digiwf-core/tree/dev/docs) and [internal](https://wiki.muenchen.de/betriebshandbuch/index.php?title=DigiWF&sfr=betriebshandbuch) are completed
- [ ] Smoketest successful (Manual E2E-Test depending on Change) 
- [ ] No Branch waste left
- [ ] [Board](https://app.zenhub.com/workspaces/digiwf-621f70bf50ea1100120b7e93/board) is up-to-date
- [ ] Openshift environments are prepared (Secrets, etc.) and release-issue is maintained

2023-12-11 16:13 UTC, lmoesle requested changes
Bei mir funktioniert das Feature noch nicht richtig. Wenn ich ein Formular ausfülle, werden die Query Parameter richtig angelegt.
Aber wenn ich die Seite dann neulade bzw. direkt auf die URL gehe werden die Formfelder nicht ausgefüllt.

**Beispiele**

- http://localhost:8084/#/process/example-all-input-fields?FormField_StartInfo=With%20this%20test%20process%20you%20start%20a%20process%20that%20assignes%20a%20usertask%20to%20the%20user%20you%20select.&FormField_User=123456789
- http://localhost:8084/#/process/example-all-input-fields?FormField_StartInfo=With%20this%20test%20process%20you%20start%20a%20process%20that%20assignes%20a%20usertask%20to%20the%20user%20you%20select.&FormField_User=123456789
- http://localhost:8084/#/process/test-grouptask-process_V01?FORMFIELD_testuser=asdfkkk 

Readonly Felder werden auch als Query Parameter gespeichert, was ein bisschen komisch ist, weil das häufig längere Beschreibungstexte sind

2023-12-13 19:10 UTC, StephanStrehlerCGI commented
ich habe jetzt nochmal mit https://ajv.js.org/strict-mode.html#unknown-keywords typemappings gemacht. 

ein Kampf bis ich das hatte. 

Bei mir geht es jetzt auch mit Zahlen. der Rest ging schon.

Das mit den Readonly felder ist ein guter punkt. das rauszufiltern wird ein Problem

2023-12-14 07:51 UTC, lmoesle commented
Ich probiere es gleich auch noch mal bei mir aus.

Das mit den Readonly Felder ist glaube ich nicht so schlimm, solange man nicht Readonly Werte überschreiben kann in dem man den Query Parameter abändert.

2023-12-14 08:26 UTC, lmoesle commented
> Bei mir funktioniert das Feature noch nicht richtig. Wenn ich ein Formular ausfülle, werden die Query Parameter richtig angelegt. Aber wenn ich die Seite dann neulade bzw. direkt auf die URL gehe werden die Formfelder nicht ausgefüllt.
> 
> **Beispiele**
> 
>     * http://localhost:8084/#/process/example-all-input-fields?FormField_StartInfo=With%20this%20test%20process%20you%20start%20a%20process%20that%20assignes%20a%20usertask%20to%20the%20user%20you%20select.&FormField_User=123456789
> 
>     * http://localhost:8084/#/process/example-all-input-fields?FormField_StartInfo=With%20this%20test%20process%20you%20start%20a%20process%20that%20assignes%20a%20usertask%20to%20the%20user%20you%20select.&FormField_User=123456789
> 
>     * http://localhost:8084/#/process/test-grouptask-process_V01?FORMFIELD_testuser=asdfkkk
> 
> 
> Readonly Felder werden auch als Query Parameter gespeichert, was ein bisschen komisch ist, weil das häufig längere Beschreibungstexte sind

Bei mir geht es leider immer noch nicht. Immer noch derselbe Fehler

2024-01-09 08:05 UTC, lmoesle commented
> > Bei mir funktioniert das Feature noch nicht richtig. Wenn ich ein Formular ausfülle, werden die Query Parameter richtig angelegt. Aber wenn ich die Seite dann neulade bzw. direkt auf die URL gehe werden die Formfelder nicht ausgefüllt.
> > **Beispiele**
> > ```
> > * http://localhost:8084/#/process/example-all-input-fields?FormField_StartInfo=With%20this%20test%20process%20you%20start%20a%20process%20that%20assignes%20a%20usertask%20to%20the%20user%20you%20select.&FormField_User=123456789
> > 
> > * http://localhost:8084/#/process/example-all-input-fields?FormField_StartInfo=With%20this%20test%20process%20you%20start%20a%20process%20that%20assignes%20a%20usertask%20to%20the%20user%20you%20select.&FormField_User=123456789
> > 
> > * http://localhost:8084/#/process/test-grouptask-process_V01?FORMFIELD_testuser=asdfkkk
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Readonly Felder werden auch als Query Parameter gespeichert, was ein bisschen komisch ist, weil das häufig längere Beschreibungstexte sind
> 
> Bei mir geht es leider immer noch nicht. Immer noch derselbe Fehler

Ich habe es nochmal ausprobiert und es geht immer noch nicht.
Lokal habe ich `npm run init`, `npm run build` und `npm run serve:tasklist` ausgeführt.

2024-01-11 10:31 UTC, lmoesle approved these changes

2024-01-12 07:49 UTC, lmoesle commented
Jetzt geht's auch bei mir 😃

2024-01-18 10:38 UTC, merged