feat: #1177 zammad init
it-at-m/digiwf-core pull request #1250
Opened 2024-01-26 13:01 UTC by dominikhorn93

### Description

Adds Tickets Integration with zammad adapter

### Reference

Issues: closes #1177

### Check-List

- [ ] All Acceptance criteria of user story are met
- [ ] JUnit tests are written (60% CodeCov)
- [ ] [Internal Review]([https://github.com/it-at-m/digiwf-core/blob/dev/CHANGELOG.md](https://confluence.muenchen.de/display/MPdZ/Review+-+DigiWF)) is maintained
- [ ] Documentations [external](https://github.com/it-at-m/digiwf-core/tree/dev/docs) and [internal](https://wiki.muenchen.de/betriebshandbuch/index.php?title=DigiWF&sfr=betriebshandbuch) are completed
- [ ] Smoketest successful (Manual E2E-Test depending on Change) 
- [ ] No Branch waste left
- [ ] [Board](https://app.zenhub.com/workspaces/digiwf-621f70bf50ea1100120b7e93/board) is up-to-date
- [ ] Openshift environments are prepared (Secrets, etc.) and release-issue is maintained

2024-02-02 09:06 UTC, lmoesle requested changes
Sieht gut aus. Der Wiremock Docker Service und die Run Configs sind eine gute Idee 👍🏻 

Mir sind einige Kleinigkeiten und Flüchtigkeitsfehler aufgefallen, schau dir die am besten nochmal an. Insbesondere die Methoden Signature des Usecases könnte zu einer Runtime Exception führen.

2024-02-02 09:06 UTC, lmoesle commented on digiwf-integrations/digiwf-ticket-integration/digiwf-ticket-integration-core/src/main/java/de/muenchen/oss/digiwf/ticket/integration/adapter/out/zammad/ZammadAdapter.java
> +        ticketUpdateDto.setArticle(articleDto);
Hier könnte man Builder aufrufe verwenden, dann sieht der Code etwas schöner aus, aber passt auch so

2024-02-02 09:06 UTC, lmoesle commented on digiwf-integrations/digiwf-ticket-integration/digiwf-ticket-integration-core/src/main/java/de/muenchen/oss/digiwf/ticket/integration/application/port/in/WriteArticleInPort.java
> +    void writeArticle(@NotBlank String ticketId, @NotNull Article article, TicketStatus status);
```suggestion
    void writeArticle(@NotBlank String ticketId, @NotNull Article article, @Nullable TicketStatus status);
```

Die Method Signature muss im Interface und in der Implementierung gleich sein, sonst kommt es zu einem Runtime Error. Im UseCase ist ein `@Nullable` mehr definiert. Entweder hier das `@Nullable` hinzufügen oder im Usecase entfernen

2024-02-02 09:06 UTC, lmoesle commented on digiwf-integrations/digiwf-ticket-integration/digiwf-ticket-integration-core/src/test/java/de/muenchen/oss/digiwf/ticket/integration/adapter/in/WriteArticleMessageProcessorTest.java
> +
```suggestion
```
Es sind ein bisschen viele Whitespaces in dem Test

2024-02-02 09:06 UTC, lmoesle commented on digiwf-integrations/digiwf-ticket-integration/digiwf-ticket-integration-core/src/test/java/de/muenchen/oss/digiwf/ticket/integration/adapter/in/WriteArticleMessageProcessorTest.java
> +
```suggestion
        Mockito.doNothing().when(writeArticleInPort).writeArticle(any(), any(), any());
```
Es sind ein bisschen viele Whitespaces in dem Test

2024-02-02 09:06 UTC, lmoesle commented on digiwf-integrations/digiwf-ticket-integration/digiwf-ticket-integration-core/src/test/java/de/muenchen/oss/digiwf/ticket/integration/application/WriteArticleUseCaseTest.java
> +public class WriteArticleUseCaseTest {
Die Klasse ist leer. Hast du hier vergessen den Test zu implementieren?

2024-02-02 09:06 UTC, lmoesle commented on digiwf-integrations/digiwf-ticket-integration/digiwf-ticket-integration-service/pom.xml
> +        <!-- alw-integration -->
```suggestion
        <!-- ticket-integration -->
```

2024-02-02 09:06 UTC, lmoesle commented on digiwf-integrations/digiwf-ticket-integration/digiwf-ticket-integration-service/pom.xml
> +        </dependency>
```suggestion
```

Die Dependency wird schon im digiwf-integration-parent definiert und dadurch in alle Module vererbt. Lombok muss man hier nicht nochmal definieren

2024-02-02 09:06 UTC, lmoesle commented on digiwf-integrations/digiwf-ticket-integration/digiwf-ticket-integration-service/src/test/resources/application-mocked-alw-service.yml
> +      alw.personeninfo:
Was hat die Ticket Integration mit Alw zu tun?

2024-02-02 09:06 UTC, lmoesle commented on digiwf-integrations/digiwf-ticket-integration/digiwf-ticket-integration-starter/src/main/java/de/muenchen/oss/digiwf/ticket/integration/configuration/TicketIntegrationAutoConfiguration.java
> +    public WriteArticleUseCase writeArticleUseCase(TicketOutPort ticketOutPort) {
```suggestion
    public WriteArticleInPort writeArticleUseCase(TicketOutPort ticketOutPort) {
```

2024-02-02 09:06 UTC, lmoesle commented on digiwf-integrations/digiwf-ticket-integration/digiwf-ticket-integration-starter/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
> +de.muenchen.oss.digiwf.zammad.ZammadAutoConfiguration
```suggestion
de.muenchen.oss.digiwf.ticket.integration.configuration.TicketIntegrationAutoConfiguration
```

2024-02-02 09:06 UTC, lmoesle commented on digiwf-integrations/digiwf-ticket-integration/digiwf-ticket-integration-zammad-api/src/test/resources/mock/docker-compose.yml
> +    container_name: wiremock-hrworks
```suggestion
    container_name: wiremock-zammad
```

2024-02-02 09:06 UTC, lmoesle commented on digiwf-integrations/digiwf-ticket-integration/pom.xml
> +    </dependencies>
```suggestion
```
Evtl. braucht man die 2 Dependencies hier nicht mehr. Die müssten auch aus dem digiwf-integration-parent kommen

2024-02-02 09:47 UTC, dominikhorn93 commented on digiwf-integrations/digiwf-ticket-integration/digiwf-ticket-integration-core/src/main/java/de/muenchen/oss/digiwf/ticket/integration/application/port/in/WriteArticleInPort.java
> +    void writeArticle(@NotBlank String ticketId, @NotNull Article article, TicketStatus status);
Also den Runtime error gab es bei mir nicht... ich entferne es trotzdem

2024-02-02 09:48 UTC, dominikhorn93 commented on digiwf-integrations/digiwf-ticket-integration/digiwf-ticket-integration-core/src/main/java/de/muenchen/oss/digiwf/ticket/integration/adapter/out/zammad/ZammadAdapter.java
> +        ticketUpdateDto.setArticle(articleDto);
das ist generiert mit OpenAPI und hat keine Builder an der Stelle

2024-02-02 09:51 UTC, lmoesle approved these changes

2024-02-12 11:40 UTC, lmoesle commented
@dominikhorn93 Mir sind noch 2 Sachen aufgefallen:
- [x] Die TicketId muss in der Url und im request Body gesetzt und gleich sein. Ansonsten bekommt man einen 400 Bad Request
- [ ] Die userid muss als Header übergeben werden, Ansonsten bekommt man auch hier einen 400 Bad Request

Ich hab's bei mir lokal mit Postman getestet und bekomme nur noch einen 403 Forbidden (The request requires higher privileges than provided by the access token). Aber so wie's aussieht geht es dann.

Den ersten Punkt habe ich schon gefixed. Wie machen wir das mit dem userid Header? Soll das ein Pflichtfeld sein oder haben wir einen Default User, wenn keiner angegeben wird?

2024-02-29 14:54 UTC, merged