feat: add red star to every field
it-at-m/digiwf-core pull request #1315
Opened 2024-02-18 22:33 UTC by dominikhorn93

### Description

Rote Sterne zu Pflichtfeldern hinzugefügt

### Reference

Issues: closes #943 

### Check-List

- [ ] All Acceptance criteria of user story are met
- [ ] JUnit tests are written (60% CodeCov)
- [ ] [Internal Review]([https://github.com/it-at-m/digiwf-core/blob/dev/CHANGELOG.md](https://confluence.muenchen.de/display/MPdZ/Review+-+DigiWF)) is maintained
- [ ] Documentations [external](https://github.com/it-at-m/digiwf-core/tree/dev/docs) and [internal](https://wiki.muenchen.de/betriebshandbuch/index.php?title=DigiWF&sfr=betriebshandbuch) are completed
- [ ] Smoketest successful (Manual E2E-Test depending on Change) 
- [ ] No Branch waste left
- [ ] [Board](https://app.zenhub.com/workspaces/digiwf-621f70bf50ea1100120b7e93/board) is up-to-date
- [ ] Openshift environments are prepared (Secrets, etc.) and release-issue is maintained

2024-02-19 11:12 UTC, lmoesle approved these changes

2024-02-19 11:18 UTC, lmoesle commented
Der Rote Stern wird bei Pflichtfeldern angezeigt.

Ich habe das Feature auch mit einem Screenreader ausprobiert. Der Stern wird mit vorgelesen ("Textfield Stern at vue") und wenn man das Feld verlässt wird die Fehlermeldung ("Dieses Feld ist ein Pflichtfeld") vorgelesen. Für mich passt das, aber nachdem ich das erste Mal einen Screenreader verwenden, weiß ich nicht, was das gewunschene Verhalten ist

2024-02-19 11:46 UTC, dominikhorn93 commented
@lmoesle ich denke ich muss noch zusätzlich das aria-required hinzufügen. Das habe ich vergessen, fällt mir gerade auf.

2024-02-19 14:24 UTC, darenegade commented on digiwf-apps/packages/components/digiwf-date-input/src/components/DwfTimeInput.vue
>    >
Fehlt hier nicht das Aria Label

2024-02-19 14:24 UTC, darenegade commented on digiwf-apps/packages/components/digiwf-dms-input/src/components/DwfDmsInput.vue
>      >
Hier fehlt auch Aria, oder

2024-02-19 14:26 UTC, darenegade commented on digiwf-apps/packages/components/digiwf-multi-file-input/src/components/DwfMultiFileInput.vue
>      >
Auch hier Aria Label

2024-02-19 14:27 UTC, darenegade commented on digiwf-apps/packages/apps/digiwf-tasklist/src/components/schema/VMultiUserInput.vue
>      >
Aria label

2024-02-19 14:28 UTC, darenegade commented on digiwf-apps/packages/apps/digiwf-tasklist/src/components/schema/VUserInput.vue
>    >
aira label

2024-02-19 14:28 UTC, darenegade commented on digiwf-apps/packages/components/digiwf-dms-input/src/components/DwfDmsInput.vue
>        @keydown.enter.prevent="addByButton"
aira label

2024-02-19 15:29 UTC, darenegade requested changes
Beim Stern muss noch `aria-hidden="true"` dazu, damit es nicht vorgelesen wird

2024-02-20 07:23 UTC, darenegade approved these changes
Sollte nun passen

2024-02-20 09:55 UTC, merged