Docs Element-Template Migration Auto Topics
it-at-m/digiwf-core pull request #1346
Opened 2024-02-22 15:39 UTC by simonhir

### Description

Dokumentation für die Migration der Element-Templates bzw. Prozesse zur Nutzung der automatischen Bestimmung der Topics.

Referenz #1168

2024-02-22 15:47 UTC, darenegade commented on docs/src/modeling/guides/element-template-migration/README.md
> +um die neue Funktionalität zu nutzen muss der Prozess aber entsprechend angepasst werden. In der normalen UI werden die
```suggestion
Die Schnittstelle wurde dabei so verändert, dass alle Prozesse die noch die alten Werte verwenden keine Probleme haben.
Um die neue Funktionalität zu nutzen, muss der Prozess aber entsprechend angepasst werden. In der normalen UI werden die
```

2024-02-22 15:48 UTC, StephanStrehlerCGI approved these changes

2024-02-22 15:48 UTC, StephanStrehlerCGI commented on docs/src/modeling/guides/element-template-migration/README.md
> +Ab Release 1.7 werden die Integrations-Topics automatisch bestimmt, dadurch müssen diese in den
muss hier Komma oder ist das neuer Satz?

2024-02-22 15:48 UTC, StephanStrehlerCGI commented on docs/src/modeling/guides/element-template-migration/README.md
> +Im gleichen Zuge wurde der alte nicht mehr benötigte Wert `app_message_name` entfernt.
alte, nicht mehr benötigte Wert,

2024-02-22 15:48 UTC, StephanStrehlerCGI commented on docs/src/modeling/guides/element-template-migration/README.md
> +Die Schnittstelle wurde dabei so verändert, dass alle Prozesse die noch die alten Werte verwenden keine Probleme haben,
. statt ,

2024-02-22 15:48 UTC, darenegade commented on docs/src/modeling/guides/element-template-migration/README.md
> +Prozess-Code übernommen. Dies muss wie nachfolgend beschrieben manuell korrigiert werden.
```suggestion
neuen Werte durch Anpassung der Element-Templates bereits angezeigt. Leider werden diese aber nicht automatisch in den
Prozess-Code übernommen. Somit muss, wie nachfolgend beschrieben, manuell korrigiert werden.
```

2024-02-22 15:52 UTC, darenegade requested changes
Vielleicht lieber doch noch eine Liste an den Integration-Names spendieren, da das navigieren auf die Integrations mühsam ist und man zudem den Badge Text nicht kopieren kann🙈

![image](https://github.com/it-at-m/digiwf-core/assets/10849776/3ebb5950-e7b2-4e58-aec8-832ad805a927)

2024-02-22 16:05 UTC, simonhir commented on docs/src/modeling/guides/element-template-migration/README.md
> +Ab Release 1.7 werden die Integrations-Topics automatisch bestimmt, dadurch müssen diese in den
Ich find als zwei Sätze liest sichs stockend, deswegen habe ich die zusammen gelegt.

2024-02-22 16:13 UTC, simonhir commented
@darenegade hab die Namen als Liste aufgenommen

2024-02-23 07:14 UTC, darenegade approved these changes

2024-02-23 07:26 UTC, merged