Test/cypress/was ist digiwf
it-at-m/digiwf-core pull request #310
Opened 2023-04-28 11:14 UTC by AnHo314

**Description**

Cypress Test: Test: Was ist DigiWF? 2min

**Reference**

Issues None

2023-05-02 11:51 UTC, darenegade commented on digiwf-cypress/cypress/e2e/was_ist_digiwf.cy.js
> +        cy.get("#password").type("");
Diese Dinge hier müssten konfigurierbar sein

2023-05-02 11:53 UTC, AnHo314 commented on digiwf-cypress/cypress/e2e/was_ist_digiwf.cy.js
> +        cy.get("#password").type("");
Ja das wird noch angepasst, sobald der User voll funktionsfähig ist, bis dahin ist der MR auf Draft

2023-05-16 13:38 UTC, darenegade commented on digiwf-cypress/cypress/fixtures/example.json
> +}
Das kann wieder aus, oder

2023-05-16 13:44 UTC, darenegade commented on digiwf-cypress/package.json
> +}
Die bräuchte noch Projekt-Specs, Run-Scripts und eventuell bessere Testing-Libs, Siehe: https://git.muenchen.de/bass/bass-e2e/-/blob/master/package.json

2023-05-16 13:44 UTC, darenegade commented on digiwf-cypress/cypress.config.js
> +    home: "https://portal-digiwf-test.apps.capk.muenchen.de/#/mytask"
Bevor wir mergen müssten wir das noch auf Lokal ändern und dann auch über die interne Pipe setzen

2023-05-16 13:46 UTC, darenegade commented on digiwf-cypress/cypress/e2e/was_ist_digiwf.cy.js
> +        // TODO: Texte bezueglich der Leerzeichen ueberpruefen
Ist das noch ein Thema oder konntest du es anders lösen?

2023-05-16 13:47 UTC, darenegade commented on digiwf-cypress/cypress/e2e/was_ist_digiwf.cy.js
> +        cy.reload(true);
Ich hatte hier eher an ein Click auf den Aktualisieren Button gedacht. Dann hat man das auch gleich getestet

2023-05-16 13:49 UTC, darenegade commented on digiwf-cypress/cypress/support/commands.js
> +    cy.wait('@dataGetFilter').its('response.statusCode').should('equal', 200);
Der Name passt nicht ganz zu dem, was der Command noch macht

2023-05-16 13:52 UTC, darenegade commented on digiwf-cypress/cypress/e2e/was_ist_digiwf.cy.js
> +        const headlineAufgaben = 'div.flex:nth-child(1) > h1:nth-child(2)';
SO etwas müsste eher ausgelagert werden, da es mit mehr Tests auch mehr benötigt wird.

Neben dem würde sich auch die Anwendung des Page-Object-Pattern sicher anbieten. Die ganzen `cy.get(..)` Aufrufe müssten wir aus dem Test rausholen, damit der fachliche Aspekt besser lesbar wird im Test und Funktionen innerhalb einer View/Page wiederverwendet werden können über versch. Tests

2023-05-16 13:54 UTC, darenegade approved these changes
Cool, dass es jetzt läuft. 👍

Da das die Basis ist für viele viele Tests müssten wir nochmal "Hirnschmalz" in die Strukturierung legen, denke ich. Dazu können wir uns gerne mal austauschen 😊

2023-05-16 13:54 UTC, darenegade requested changes
Wrong Button 😅

2023-05-16 14:00 UTC, AnHo314 commented on digiwf-cypress/cypress/e2e/was_ist_digiwf.cy.js
> +        // TODO: Texte bezueglich der Leerzeichen ueberpruefen
Das ist noch Thema, dachte das wird vllt noch im Projekt geändert.

2023-05-16 14:01 UTC, AnHo314 commented on digiwf-cypress/cypress/e2e/was_ist_digiwf.cy.js
> +        cy.reload(true);
Der ist damit auch nur sehr indirekt getestet aber das kann ich gerne einbauen

2023-05-16 14:01 UTC, darenegade commented on digiwf-cypress/cypress/e2e/was_ist_digiwf.cy.js
> +        // TODO: Texte bezueglich der Leerzeichen ueberpruefen
Müsste man schauen, woher das kommt. Ist etwas komisch, dass es nicht konsistent ist. Dann lassen wir das ToDo drin

2023-05-24 14:23 UTC, darenegade commented on digiwf-cypress/cypress/e2e/was_ist_digiwf.cy.js
> +        meineAufgaben.clickNavbar();
Wozu der Schritt?

2023-05-24 14:24 UTC, darenegade commented on digiwf-cypress/cypress/e2e/was_ist_digiwf.cy.js
> +        aktuellDigiWFErleben.clickNavbar();
Hier auch

2023-05-24 14:25 UTC, darenegade commented on digiwf-cypress/cypress/e2e/was_ist_digiwf.cy.js
> +        meineAufgaben.clickNavbar();
Hier auch

2023-05-24 14:26 UTC, darenegade commented on digiwf-cypress/cypress/e2e/was_ist_digiwf.cy.js
> +        cy.reload(true);
Wenn es nicht klappt, dann passt es mit dem Kommentar auch

2023-05-24 14:28 UTC, darenegade commented on digiwf-cypress/cypress/pages/page.js
> +    }
Das erscheint mir hier nicht richtig, Nicht jede Page hat eine Liste (von offenen Tasks)

2023-05-24 14:30 UTC, darenegade commented on digiwf-cypress/cypress/pages/page.js
> +    }
Wenn es wiederverwendet werden soll auf allen Pages mit Liste, dann müsste man es weiter ableiten als z.B. ListPage

2023-05-24 14:30 UTC, darenegade commented on digiwf-cypress/cypress/pages/page.js
> +    }
Das ist auch etwas für Listen und gilt nicht auf jeder Page

2023-05-24 14:32 UTC, darenegade requested changes
Noch etwas aufräumen bei der Hierarchie, aber sonst schaut es schon sehr gut aus.

2023-05-25 13:39 UTC, AnHo314 commented on digiwf-cypress/cypress/pages/page.js
> +    }
Wenn ich das richtig gesehen habe immer für die konkrete Seite, da andere Dinge im Hintergrund geladen werden (instance/definition/task)

2023-05-25 13:40 UTC, AnHo314 commented on digiwf-cypress/cypress/pages/page.js
> +    }
Hier schaue ich in der seitenleiste nach, ob hinter meine Aufgaben aktuell ein Wert steht. Und die Seitenleistenkomponente is ja auf allen Seiten vorhanden.

2023-05-25 13:42 UTC, darenegade commented on digiwf-cypress/cypress/pages/page.js
> +    }
Mir geht es nicht darum, dass der Check falsch ist, sondern das er hier doch in der Page für alle Views gilt, was aber nicht bei jeder View der Fall ist. Vielleicht reden wir aneinander vorbei😅

2023-05-25 13:48 UTC, darenegade commented on digiwf-cypress/cypress/pages/page.js
> +    }
> Hier schaue ich in der seitenleiste nach, ob hinter meine Aufgaben aktuell ein Wert steht.

ahhhhhhhhh.......sorry, dann habe ich den check falsch verstanden.

Vielleicht dann einfach einen besseren Namen wählen, da nicht klar ist, was die startCondition ist

2023-05-25 15:03 UTC, darenegade commented on digiwf-cypress/cypress/e2e/was_ist_digiwf.cy.js
> +        aktuellDigiWFErleben.clickNavbar();
Rückinfo @AnHo314 : Hier geht es darum, dass die NavBar geöffnet wird, wenn sie wegen zu kleinem Display geschlossen ist.

Dann müsste die Funktion aber "openNavbar" heißen. Wobei dass in die "openXXX" kommen müsste mit einem Check, ob die Navbar offen ist oder nicht und dann öffnen, wenn nicht, damit es für beide Varianten passt

2023-05-25 15:03 UTC, darenegade commented on digiwf-cypress/cypress/e2e/was_ist_digiwf.cy.js
> +        meineAufgaben.clickNavbar();
https://github.com/it-at-m/digiwf-core/pull/310/files#r1205654198

2023-05-25 15:03 UTC, darenegade commented on digiwf-cypress/cypress/e2e/was_ist_digiwf.cy.js
> +        meineAufgaben.clickNavbar();
https://github.com/it-at-m/digiwf-core/pull/310/files#r1205654198

2023-05-25 15:06 UTC, darenegade commented
> Noch etwas aufräumen bei der Hierarchie

Hier bin ich noch davon ausgegangen, dass die CheckCondition-Funktion nur für Listen gilt. Das konnte geklärt werden und ist hinfällig:

https://github.com/it-at-m/digiwf-core/pull/310#discussion_r1205550642

2023-05-25 15:06 UTC, darenegade commented on digiwf-cypress/cypress/e2e/was_ist_digiwf.cy.js
> +        meineAufgaben.checkIfTasksAreEmpty();
👍

2023-05-30 08:03 UTC, darenegade approved these changes
Passt, gute Arbeit👍

2023-05-30 09:04 UTC, merged