feature(#398): support method put for file upload
it-at-m/digiwf-core pull request #448
Opened 2023-06-13 13:24 UTC by lmoesle

**Description**

Short description or comments

**Reference**

Issues #398

2023-06-14 09:50 UTC, lehju reviewed
Aktuell wird immer POST verwendet, auch wenn die Datei bereits existiert und ersetzt werden soll. Daher kommt es zu einer Fehlermeldung. Es muss noch überprüft werden, ob die Datei bereits existiert und in diesem Fall PUT verwendet werden.

2023-06-15 14:14 UTC, zambrovski approved these changes

2023-06-15 14:42 UTC, darenegade commented
Fehlt dann hier nicht noch die UI Anpassung?

2023-06-16 05:34 UTC, lehju commented
Genau, hier fehlt noch der Aufruf der PUT Methode.

2023-06-16 06:56 UTC, darenegade requested changes
Bitte noch die UI Anpassung machen, da die Änderung hier sonst nichts bewirkt und das Ticket nicht erledigt. Danke

2023-07-02 10:07 UTC, lmoesle commented
@darenegade Im Ticket steht nichts von UI Anpassung. Kannst du das da bitte noch nachtragen oder ein zweites Ticket aufmachen, damit das auch irgendwo dokumentiert ist?

2023-07-21 07:30 UTC, darenegade approved these changes
UI  Anpassung ziehen wir hier raus, da es aufwändiger ist, als gedacht

2023-07-21 15:12 UTC, merged