Feature/#497 process api pagination
it-at-m/digiwf-core pull request #465
Opened 2023-06-16 13:33 UTC by StephanStrehlerCGI

**Description**

Short description or comments

**Reference**
https://app.zenhub.com/workspaces/digiwf-621f70bf50ea1100120b7e93/issues/gh/it-at-m/digiwf-project/492

2023-06-21 14:25 UTC, darenegade commented on digiwf-engine/digiwf-engine-service/src/main/java/io/muenchendigital/digiwf/process/definition/domain/mapper/ServiceDefinitionPageMapper.java
> +        ).collect(Collectors.toList());
Bekommen wir das nicht aus der DB🤔

2023-06-21 14:27 UTC, darenegade requested changes
Alles im allem okay, aber ich wundere mich, dass wir das Paging nicht über die DB Abfrage machen. Das könnte uns doch potentiell um die Ohren fliegen.

Warum hast du dich für diese Lösung entschieden?

2023-06-21 14:37 UTC, darenegade commented
Man könnte hier auch mit ListPage arbeiten

![image](https://github.com/it-at-m/digiwf-core/assets/10849776/a11df945-c2b0-4541-8cc4-bfc2e4ed26ac)

https://github.com/it-at-m/digiwf-core/blob/4256e2f65d568c437246449e88773a6e7d1becc0/digiwf-engine/digiwf-engine-service/src/main/java/io/muenchendigital/digiwf/process/definition/domain/service/ServiceDefinitionService.java#L107

2023-06-21 19:18 UTC, StephanStrehlerCGI commented
Hallo, 
Pagination aus der DB ist natürlich immer die saubere Lösung. In dem Fall müssen wird aber das Ergebnis nachdem wir die Prozessdefinition aus der DB geladen haben anschließend noch durch die Zugriffskontrolle filtern (durch den ServiceDefinitionAuthService Service). An sich ist das wirklich doof (1+n DB Abfragen). 
Um das zu lösen müssten wir wieder komplett eigene DB Abfragen mit CriteriaQuery und co bauen. 
Das macht aktuell aus meiner Sicht wenig Sinn. Das eigentliche Handling für Prozessdefinitionen muss sowieso noch einmal durch ein Refactoring umgebaut werden soll. 

Hauptproblem was bei den E2e Tests vorallem auftritt sind Performance Probleme bei der Datenübertragung und bei dem Datenhandling im Frontend. Das hätten wir damit beseitigt.

2023-06-22 11:09 UTC, darenegade commented
@zambrovski Hast du hier noch einen Tipp, sonst würde ich das so akzeptieren

2023-06-22 11:23 UTC, zambrovski commented
Ich glaub das passt zum jetzigen Zeitpunkt. Mit der Aussicht das wir es komplett umbauen werden würde ich jetzt auch nicht mehr investieren.

2023-06-22 11:24 UTC, darenegade approved these changes
Passt

2023-06-23 17:48 UTC, merged