Add okewo integration
it-at-m/digiwf-core pull request #613
Opened 2023-08-23 12:10 UTC by axd4

**Description**

Short description or comments

**Reference**

Issues #XXX

2023-09-13 08:52 UTC, StephanStrehlerCGI commented
Hallo, 
mein Review des Merge Requests sind mir noch ein paar Punkte aufgefallen: 

1. Ordner und Modul gleich benennen 
2. Bitte den Gen Ordner nicht mit einchecken
3. Variablen bitte in englischer Sprache 
4. Tests für Integration Service schreiben

Könntest du die genannten Punkte noch lösen?

Vielen Dank! 

Bei Fragen, gern melden. 

Grüße

Stephan

2023-09-13 08:52 UTC, StephanStrehlerCGI requested changes

2023-09-13 08:52 UTC, StephanStrehlerCGI commented on digiwf-integrations/digiwf-ok.ewo-integration/digiwf-okewo-integration-core/src/main/java/de/muenchen/oss/digiwf/okewo/integration/service/PropertiesService.java
> +public class PropertiesService {
Könntest du die Klasse umbenennen, da es im Core kein Service ist. 
Name könnte bsp: PropertiesService sein.

2023-09-13 08:52 UTC, StephanStrehlerCGI commented on digiwf-integrations/digiwf-ok.ewo-integration/digiwf-okewo-integration-core/src/main/java/de/muenchen/oss/digiwf/okewo/integration/service/PropertiesService.java
> +@RequiredArgsConstructor
Könntest du hier den Constructor händisch schreiben, dann verschwindet in Idea die Fehlermeldung, dass Spring die Bean nicht finden kann.

2023-09-13 08:52 UTC, StephanStrehlerCGI commented on digiwf-integrations/digiwf-ok.ewo-integration/digiwf-okewo-integration-core/src/main/java/de/muenchen/oss/digiwf/okewo/integration/service/PropertiesService.java
> +        benutzerType.setBenutzerId(this.getBenutzerId());
Hier bräuchtest du rein theoretisch den Getter nicht.

2023-09-13 08:52 UTC, StephanStrehlerCGI commented on digiwf-integrations/digiwf-ok.ewo-integration/digiwf-okewo-integration-core/src/test/java/de/muenchen/oss/digiwf/okewo/integration/service/PropertiesServiceTest.java
> +@MockitoSettings(strictness = Strictness.LENIENT)
Die beiden Annotations sind hier nicht nötig.

2023-09-13 08:52 UTC, StephanStrehlerCGI commented on digiwf-integrations/digiwf-ok.ewo-integration/digiwf-okewo-integration-core/src/test/java/de/muenchen/oss/digiwf/okewo/integration/service/OkEwoPersonServiceTest.java
> +    private OkEwoPersonRepository okEwoPersonRepository;
wenn du stattdessen `private final OkEwoPersonRepository okEwoPersonRepository = mock(OkEwoPersonRepository.class);` schreibst und dann OkEwoPersonService direkt initialisierst benötigst du weder die Annotations über der Klasse noch die @BeforeEach Methode.

2023-09-13 08:52 UTC, StephanStrehlerCGI commented on digiwf-integrations/digiwf-ok.ewo-integration/digiwf-okewo-integration-core/src/test/java/de/muenchen/oss/digiwf/okewo/integration/service/OkEwoPersonErweitertServiceTest.java
> +    private OkEwoPersonErweitertRepository okEwoPersonErweitertRepository;
wenn du stattdessen private final `private final OkEwoPersonErweitertRepository okEwoPersonErweitertRepository = mock(OkEwoPersonErweitertRepository.class);`  schreibst und dann OkEwoPersonService direkt initialisierst benötigst du weder die Annotations über der Klasse noch die @beforeeach Methode.

2023-09-20 14:12 UTC, StephanStrehlerCGI commented on digiwf-integrations/digiwf-ok.ewo-integration/digiwf-okewo-integration-core/src/main/java/de/muenchen/oss/digiwf/okewo/integration/service/PropertiesService.java
> +public class PropertiesService {
PropertiesProvider mein ich

2023-09-20 15:10 UTC, StephanStrehlerCGI commented
PropertiesServiceTemplate

2023-09-26 07:49 UTC, StephanStrehlerCGI approved these changes

2023-09-26 07:54 UTC, StephanStrehlerCGI approved these changes

2023-09-27 07:00 UTC, lmoesle approved these changes
Ich approve den PR schon mal, aber bitte noch die Kommentare von mir in der Release Pipeline beachten

2023-09-27 07:00 UTC, lmoesle commented on .github/workflows/workflow-release-services.yaml
> +        uses: docker/build-push-action@v4
```suggestion
        uses: docker/build-push-action@v5
````

2023-09-27 07:00 UTC, lmoesle commented on .github/workflows/workflow-release-services.yaml
> +        uses: docker/build-push-action@v4
Am besten gleich v5 nehmen, wie bei den ganzen anderen docker build and pushs

2023-09-27 07:00 UTC, lmoesle commented on .github/workflows/workflow-release-services.yaml
> +          tags: itatm/digiwf-okewo-integration-service:${{ env.RELEASE_VERSION }},itatm/digiwf-okewo-integration-service:dev
````suggestion
          tags: itatm/digiwf-okewo-integration-service:${{ inputs.release-version }},itatm/digiwf-okewo-integration-service:dev
````

2023-09-27 07:00 UTC, lmoesle commented on .github/workflows/workflow-release-services.yaml
>            tags: itatm/digiwf-dms-integration-service:${{ env.RELEASE_VERSION }},itatm/digiwf-dms-integration-service:dev
````suggestion
          tags: itatm/digiwf-dms-integration-service:${{ inputs.release-version }},itatm/digiwf-dms-integration-service:dev
````

2023-09-27 07:00 UTC, lmoesle commented on .github/workflows/workflow-release-services.yaml
> +          tags: itatm/digiwf-okewo-integration-service:${{ env.RELEASE_VERSION }},itatm/digiwf-okewo-integration-service:dev
Copy & Paste Error von oben

2023-09-27 07:00 UTC, lmoesle commented on .github/workflows/workflow-release-services.yaml
>            tags: itatm/digiwf-dms-integration-service:${{ env.RELEASE_VERSION }},itatm/digiwf-dms-integration-service:dev
Hat nichts mit der Integration zu tun, aber hier passt die Release Version auch nicht

2023-09-27 07:08 UTC, lmoesle reviewed
Die maven Versions passen nicht. Bitte noch die Integration auf Version 1.1.0-SNAPSHOT anpassen

2023-09-27 07:08 UTC, lmoesle commented on digiwf-integrations/digiwf-okewo-integration/pom.xml
> +        <version>0.18.0-SNAPSHOT</version>
````suggestion
        <version>1.1.0-SNAPSHOT</version>
````

2023-09-27 07:08 UTC, lmoesle commented on digiwf-integrations/digiwf-okewo-integration/pom.xml
> +    <version>0.18.0-SNAPSHOT</version>
````suggestion
    <version>1.1.0-SNAPSHOT</version>
````

2023-09-27 07:08 UTC, lmoesle commented on digiwf-integrations/digiwf-okewo-integration/digiwf-okewo-integration-starter/pom.xml
> +        <version>0.18.0-SNAPSHOT</version>
`````suggestion
        <version>1.1.0-SNAPSHOT</version>
````

2023-09-27 07:08 UTC, lmoesle commented on digiwf-integrations/digiwf-okewo-integration/digiwf-okewo-integration-service/pom.xml
> +        <version>0.18.0-SNAPSHOT</version>
`````suggestion
        <version>1.1.0-SNAPSHOT</version>
````

2023-09-27 07:08 UTC, lmoesle commented on digiwf-integrations/digiwf-okewo-integration/digiwf-okewo-integration-core/pom.xml
> +        <version>0.18.0-SNAPSHOT</version>
`````suggestion
        <version>1.1.0-SNAPSHOT</version>
````

2023-10-04 12:37 UTC, merged