Add Address-Service Integration
it-at-m/digiwf-core pull request #620
Opened 2023-08-25 10:12 UTC by ThoGro

**Description**

Add digiwf-address-service-integration to digiwf-core integrations

2023-09-14 15:42 UTC, StephanStrehlerCGI commented
Hallo,
mein Review des Merge Requests sind mir noch ein paar Punkte aufgefallen:

1. Bitte den Gen Ordner nicht mit einchecken
2. Variablen bitte in englischer Sprache
3. Tests für Integration Service schreiben

Könntest du die genannten Punkte noch lösen?

Vielen Dank!

Bei Fragen, gern melden.

Grüße

Stephan

2023-09-14 15:49 UTC, StephanStrehlerCGI requested changes

2023-09-14 15:49 UTC, StephanStrehlerCGI commented on digiwf-integrations/digiwf-address-service-integration/digiwf-address-service-integration-service/src/main/java/de/muenchen/oss/digiwf/address/service/integration/api/dto/request/AbstractRequestDto.java
> +@JsonSubTypes({
Wozu ist das an der Stelle notwendig?

2023-10-23 15:20 UTC, StephanStrehlerCGI commented on digiwf-integrations/digiwf-address-integration/digiwf-address-integration-service/Dockerfile
> +FROM registry.access.redhat.com/ubi8/openjdk-11:latest
Hier müssen wir schauen, wenn JDK 17 schon gemerged wurde bevor der hier gemerged ist, muss hier dann noch die 17 hin

2023-10-23 15:20 UTC, StephanStrehlerCGI commented on digiwf-integrations/digiwf-address-integration/digiwf-address-integration-client/src/main/java/de/muenchen/oss/digiwf/address/integration/client/impl/AddressGermanyImpl.java
> +            log.error(message);
macht hier das doppelte logging sinn? 

Oder generell das Logging?

2023-10-23 15:20 UTC, StephanStrehlerCGI commented on digiwf-integrations/digiwf-address-integration/digiwf-address-integration-client/src/main/java/de/muenchen/oss/digiwf/address/integration/client/model/request/SearchAddressesGermanyModel.java
> +    private String gemeindeschluessel;
Gibt es hier nicht irgendein englischen namen für?

2023-10-24 06:46 UTC, lmoesle commented on digiwf-integrations/digiwf-address-integration/digiwf-address-integration-client/src/main/java/de/muenchen/oss/digiwf/address/integration/client/impl/AddressGermanyImpl.java
> +            log.error(message);
Stimmt, du hast Recht. Ich hab das logging zu debug geändert

2023-10-24 07:00 UTC, lmoesle commented on digiwf-integrations/digiwf-address-integration/digiwf-address-integration-client/src/main/java/de/muenchen/oss/digiwf/address/integration/client/model/request/SearchAddressesGermanyModel.java
> +    private String gemeindeschluessel;
Man könnte das zu *communityKey* ändern, aber der gemeindeschluessel ist etwas sehr deutsches. Ich weiß nicht, ob das so sinnvoll ist das umzubenennen

2023-10-27 07:53 UTC, StephanStrehlerCGI approved these changes

2023-10-27 09:22 UTC, merged