Feature/update jdk 17
it-at-m/digiwf-core pull request #826
Opened 2023-10-09 14:21 UTC by zambrovski

### Description

Adds JDK 17 support

### Reference

Issues: #824

2023-10-13 06:41 UTC, darenegade requested changes
Dockerfiles müssen noch angepasst werden

2023-10-13 06:45 UTC, darenegade requested changes
POMs müssen auch noch angepasst werden.

2023-10-16 11:43 UTC, darenegade commented on digiwf-engine/digiwf-engine-service/src/main/resources/bausteine/dms/dokumentstornieren/DokumentStornierenV01.bpmn
> +task.setVariable("dms_user_login",sachbearbeitung);</camunda:script>
Shouldn't it be "task.**getExecution(**).getVariable(...)"? Otherwise the behavior changes because the scope is different.

2023-10-20 14:44 UTC, StephanStrehlerCGI commented on digiwf-engine/digiwf-engine-service/src/main/resources/bausteine/dms/dokumentstornieren/DokumentStornierenV01.bpmn
> +task.setVariable("dms_user_login",sachbearbeitung);</camunda:script>
done

2023-10-20 14:47 UTC, StephanStrehlerCGI commented
Dockerfiles angepasst. POMs verstehen ich nicht, in der Root POM ist schon auf Java 17 gewechselt. an anderen Stellen habe ich die Java version definition nicht gefunden.

2023-10-23 06:29 UTC, darenegade commented
> POMs verstehen ich nicht, in der Root POM ist schon auf Java 17 gewechselt

Passt dann 👍

2023-10-23 11:33 UTC, dominikhorn93 commented on digiwf-engine/digiwf-engine-service/src/main/resources/bausteine/dms/dokumentstornieren/DokumentStornierenV02.bpmn
> +          <camunda:script scriptFormat="javascript">sachbearbeitung= task.getVariable("FormField_Neue_Sachbearbeitung");
task.getExecution().getVariable

task.getExection().setVariable

2023-10-23 11:33 UTC, dominikhorn93 commented on digiwf-engine/digiwf-engine-service/src/main/resources/bausteine/dms/schriftstueckupdaten/SchriftstueckUpdatenV01.bpmn
> -task.execution.setVariable("dms_user_login",sachbearbeitung);</camunda:script>
task.getExecution().getVariable

task.getExection().setVariable

2023-10-23 11:34 UTC, dominikhorn93 commented on digiwf-engine/digiwf-engine-service/src/main/resources/bausteine/dms/schriftstueckupdaten/SchriftstueckUpdatenV02.bpmn
> +          <camunda:script scriptFormat="javascript">sachbearbeitung= task.getVariable("FormField_Neue_Sachbearbeitung");
task.getExecution().getVariable

task.getExection().setVariable

2023-10-23 11:35 UTC, dominikhorn93 requested changes
Ich vermute man muss die Aufrufe in den BPMNs auf task.getExecution()** anpassen?

2023-10-23 14:45 UTC, dominikhorn93 approved these changes
LGTM

2023-10-23 15:11 UTC, darenegade approved these changes
👍

2023-10-23 15:12 UTC, merged